(dp1
S'output'
p2
S"<type 'exceptions.NameError'> global name 'value' is not defined"
p3
sS'layer'
p4
S'/Users/ecain/Projects/SOTA/web2py/applications/sota/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x109ed13b0, file "/Users/ecain/Projects/SOTA/web2py/applications/sota/controllers/default.py:ecu_list", line 10>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/Users/ecain/Projects/SOTA/web2py/gluon/restricted.py", line 216, in restricted\n    exec(ccode, environment)\n  File "/Users/ecain/Projects/SOTA/web2py/applications/sota/controllers/default.py:ecu_list", line 210, in <module>\n  File "/Users/ecain/Projects/SOTA/web2py/gluon/globals.py", line 405, in <lambda>\n    self._caller = lambda f: f()\n  File "/Users/ecain/Projects/SOTA/web2py/applications/sota/controllers/default.py:ecu_list", line 200, in ecu_list\nNameError: global name \'value\' is not defined\n'
p11
s.